# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

recorder:
  db_url: !secret recorder_db_url

ffmpeg:

camera:
  - platform: ffmpeg
    name: entry_cam_main
    input: /dev/video0
    extra_arguments: -f v4l2 -input_format h264 -video_size 1920x1080 -framerate 30 -use_wallclock_as_timestamps 1 -fflags +genpts