Remote API enabled: false
Hue Essentials key: 87c0b33a32ec11ef93032ccf671f8528
discovery: true
mqtt:
  enabled: false
deconz:
  enabled: false
alarm:
  enabled: false
  lasttriggered: 0
port:
  enabled: false
  ports:
  - 80
apiUsers: {}
apiversion: 1.65.0
name: DiyHue Bridge
netmask: 255.255.255.0
swversion: '1965017030'
timezone: Europe/London
linkbutton:
  lastlinkbuttonpushed: 1719318623
users:
  admin@diyhue.org:
    password: pbkdf2:sha256:150000$bqqXSOkI$199acdaf81c18f6ff2f29296872356f4eb78827784ce4b3f3b6262589c788742
hue: {}
tradfri: {}
homeassistant:
  enabled: false
yeelight:
  enabled: true
native_multi:
  enabled: true
tasmota:
  enabled: true
wled:
  enabled: true
shelly:
  enabled: true
esphome:
  enabled: true
hyperion:
  enabled: true
tpkasa:
  enabled: true
elgato:
  enabled: true
zigbee_device_discovery_info:
  status: ready
swupdate2:
  autoinstall:
    'on': true
  bridge:
    lastinstall: '2024-06-25T12:14:54'
    state: noupdates
  checkforupdate: false
  lastchange: '2024-06-25T12:14:54'
  state: noupdates
  install: false
ipaddress: 10.50.165.142
gateway: 10.50.165.1
mac: 2c:cf:67:1f:85:28
bridgeid: 2CCF67FFFE1F8528
whitelist:
  6ed6f39632ee11ef93032ccf671f8528:
    name: WebUi
    client_key: null
    create_date: '2024-06-25T12:14:54'
    last_use_date: '2024-06-25T12:30:24'
  b29e6ab432ee11ef93032ccf671f8528:
    name: Hue#iPhone
    client_key: EA7E87789B8546D699CF936BBCA11C0B
    create_date: '2024-06-25T12:14:54'
    last_use_date: '2024-06-25T12:30:29'
portalservices: false
